<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dinkes_prov extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Dinkes_prov_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','dinkes_prov/t_dinkes_prov_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Dinkes_prov_model->json();
    }

    public function read($id) 
    {
        $row = $this->Dinkes_prov_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_dinkes_prov' => $row->id_dinkes_prov,
		'nama_dinkes_prov' => $row->nama_dinkes_prov,
	    );
            $this->template->load('template','dinkes_prov/t_dinkes_prov_read', $data);
        } else {
            notif('2');
            redirect(site_url('dinkes_prov'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('dinkes_prov/create_action'),
	    'id_dinkes_prov' => set_value('id_dinkes_prov'),
	    'nama_dinkes_prov' => set_value('nama_dinkes_prov'),
	);
        $this->template->load('template','dinkes_prov/t_dinkes_prov_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_dinkes_prov' => $this->input->post('nama_dinkes_prov',TRUE),
	    );

            $this->Dinkes_prov_model->insert($data);
            notif('0');
            redirect(site_url('dinkes_prov'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Dinkes_prov_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Perbaharui',
                'action' => site_url('dinkes_prov/update_action'),
		'id_dinkes_prov' => set_value('id_dinkes_prov', $row->id_dinkes_prov),
		'nama_dinkes_prov' => set_value('nama_dinkes_prov', $row->nama_dinkes_prov),
	    );
            $this->template->load('template','dinkes_prov/t_dinkes_prov_form', $data);
        } else {
            notif('2');
            redirect(site_url('dinkes_prov'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_dinkes_prov', TRUE));
        } else {
            $data = array(
		'nama_dinkes_prov' => $this->input->post('nama_dinkes_prov',TRUE),
	    );

            $this->Dinkes_prov_model->update($this->input->post('id_dinkes_prov', TRUE), $data);
            notif('1');
            redirect(site_url('dinkes_prov'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Dinkes_prov_model->get_by_id($id);

        if ($row) {
            $this->Dinkes_prov_model->delete($id);
            notif('3');
            redirect(site_url('dinkes_prov'));
        } else {
            notif('2');
            redirect(site_url('dinkes_prov'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_dinkes_prov', 'nama dinkes prov', 'trim|required');

	$this->form_validation->set_rules('id_dinkes_prov', 'id_dinkes_prov', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Dinkes_prov.php */
/* Location: ./application/controllers/Dinkes_prov.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:09:21 */
/* http://harviacode.com */