<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Instansi_lembaga extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Instansi_lembaga_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','instansi_lembaga/t_instansi_lembaga_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Instansi_lembaga_model->json();
    }

    public function read($id) 
    {
        $row = $this->Instansi_lembaga_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_instansi_lembaga' => $row->id_instansi_lembaga,
		'nama_instansi_lembaga' => $row->nama_instansi_lembaga,
	    );
            $this->template->load('template','instansi_lembaga/t_instansi_lembaga_read', $data);
        } else {
            notif('2');
            redirect(site_url('instansi_lembaga'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('instansi_lembaga/create_action'),
	    'id_instansi_lembaga' => set_value('id_instansi_lembaga'),
	    'nama_instansi_lembaga' => set_value('nama_instansi_lembaga'),
	);
        $this->template->load('template','instansi_lembaga/t_instansi_lembaga_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_instansi_lembaga' => $this->input->post('nama_instansi_lembaga',TRUE),
	    );

            $this->Instansi_lembaga_model->insert($data);
            notif('0');
            redirect(site_url('instansi_lembaga'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Instansi_lembaga_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Perbaharui',
                'action' => site_url('instansi_lembaga/update_action'),
		'id_instansi_lembaga' => set_value('id_instansi_lembaga', $row->id_instansi_lembaga),
		'nama_instansi_lembaga' => set_value('nama_instansi_lembaga', $row->nama_instansi_lembaga),
	    );
            $this->template->load('template','instansi_lembaga/t_instansi_lembaga_form', $data);
        } else {
            notif('2');
            redirect(site_url('instansi_lembaga'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_instansi_lembaga', TRUE));
        } else {
            $data = array(
		'nama_instansi_lembaga' => $this->input->post('nama_instansi_lembaga',TRUE),
	    );

            $this->Instansi_lembaga_model->update($this->input->post('id_instansi_lembaga', TRUE), $data);
            notif('1');
            redirect(site_url('instansi_lembaga'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Instansi_lembaga_model->get_by_id($id);

        if ($row) {
            $this->Instansi_lembaga_model->delete($id);
            notif('3');
            redirect(site_url('instansi_lembaga'));
        } else {
            notif('2');
            redirect(site_url('instansi_lembaga'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_instansi_lembaga', 'nama instansi lembaga', 'trim|required');

	$this->form_validation->set_rules('id_instansi_lembaga', 'id_instansi_lembaga', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Instansi_lembaga.php */
/* Location: ./application/controllers/Instansi_lembaga.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:10:21 */
/* http://harviacode.com */