<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_kegiatan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Jenis_kegiatan_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','jenis_kegiatan/t_jenis_kegiatan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jenis_kegiatan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jenis_kegiatan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_jenis_kegiatan' => $row->id_jenis_kegiatan,
		'nama_kegiatan' => $row->nama_kegiatan,
	    );
            $this->template->load('template','jenis_kegiatan/t_jenis_kegiatan_read', $data);
        } else {
            notif('2');
            redirect(site_url('jenis_kegiatan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('jenis_kegiatan/create_action'),
	    'id_jenis_kegiatan' => set_value('id_jenis_kegiatan'),
	    'nama_kegiatan' => set_value('nama_kegiatan'),
	);
        $this->template->load('template','jenis_kegiatan/t_jenis_kegiatan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kegiatan' => $this->input->post('nama_kegiatan',TRUE),
	    );

            $this->Jenis_kegiatan_model->insert($data);
            notif('0');
            redirect(site_url('jenis_kegiatan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jenis_kegiatan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Perbaharui',
                'action' => site_url('jenis_kegiatan/update_action'),
		'id_jenis_kegiatan' => set_value('id_jenis_kegiatan', $row->id_jenis_kegiatan),
		'nama_kegiatan' => set_value('nama_kegiatan', $row->nama_kegiatan),
	    );
            $this->template->load('template','jenis_kegiatan/t_jenis_kegiatan_form', $data);
        } else {
            notif('2');
            redirect(site_url('jenis_kegiatan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jenis_kegiatan', TRUE));
        } else {
            $data = array(
		'nama_kegiatan' => $this->input->post('nama_kegiatan',TRUE),
	    );

            $this->Jenis_kegiatan_model->update($this->input->post('id_jenis_kegiatan', TRUE), $data);
            notif('1');
            redirect(site_url('jenis_kegiatan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jenis_kegiatan_model->get_by_id($id);

        if ($row) {
            $this->Jenis_kegiatan_model->delete($id);
            notif('3');
            redirect(site_url('jenis_kegiatan'));
        } else {
            notif('2');
            redirect(site_url('jenis_kegiatan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kegiatan', 'nama kegiatan', 'trim|required');

	$this->form_validation->set_rules('id_jenis_kegiatan', 'id_jenis_kegiatan', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Jenis_kegiatan.php */
/* Location: ./application/controllers/Jenis_kegiatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:11:25 */
/* http://harviacode.com */