<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Satuan_kerja extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Satuan_kerja_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','satuan_kerja/t_satuan_kerja_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Satuan_kerja_model->json();
    }

    public function read($id) 
    {
        $row = $this->Satuan_kerja_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_satuan_kerja' => $row->id_satuan_kerja,
		'id_unit_utama' => $row->id_unit_utama,
		'nama_satuan_kerja' => $row->nama_satuan_kerja,
	    );
            $this->template->load('template','satuan_kerja/t_satuan_kerja_read', $data);
        } else {
            notif('2');
            redirect(site_url('satuan_kerja'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('satuan_kerja/create_action'),
	    'id_satuan_kerja' => set_value('id_satuan_kerja'),
	    'id_unit_utama' => set_value('id_unit_utama'),
	    'nama_satuan_kerja' => set_value('nama_satuan_kerja'),
	);
        $this->template->load('template','satuan_kerja/t_satuan_kerja_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_unit_utama' => $this->input->post('id_unit_utama',TRUE),
		'nama_satuan_kerja' => $this->input->post('nama_satuan_kerja',TRUE),
	    );

            $this->Satuan_kerja_model->insert($data);
            notif('0');
            redirect(site_url('satuan_kerja'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Satuan_kerja_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Perbaharui',
                'action' => site_url('satuan_kerja/update_action'),
		'id_satuan_kerja' => set_value('id_satuan_kerja', $row->id_satuan_kerja),
		'id_unit_utama' => set_value('id_unit_utama', $row->id_unit_utama),
		'nama_satuan_kerja' => set_value('nama_satuan_kerja', $row->nama_satuan_kerja),
	    );
            $this->template->load('template','satuan_kerja/t_satuan_kerja_form', $data);
        } else {
            notif('2');
            redirect(site_url('satuan_kerja'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_satuan_kerja', TRUE));
        } else {
            $data = array(
		'id_unit_utama' => $this->input->post('id_unit_utama',TRUE),
		'nama_satuan_kerja' => $this->input->post('nama_satuan_kerja',TRUE),
	    );

            $this->Satuan_kerja_model->update($this->input->post('id_satuan_kerja', TRUE), $data);
            notif('1');
            redirect(site_url('satuan_kerja'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Satuan_kerja_model->get_by_id($id);

        if ($row) {
            $this->Satuan_kerja_model->delete($id);
            notif('3');
            redirect(site_url('satuan_kerja'));
        } else {
            notif('2');
            redirect(site_url('satuan_kerja'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_unit_utama', 'id unit utama', 'trim|required');
	$this->form_validation->set_rules('nama_satuan_kerja', 'nama satuan kerja', 'trim|required');

	$this->form_validation->set_rules('id_satuan_kerja', 'id_satuan_kerja', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Satuan_kerja.php */
/* Location: ./application/controllers/Satuan_kerja.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:13:43 */
/* http://harviacode.com */