<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Timrekom extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Timrekom_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','timrekom/v_timrekom_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Timrekom_model->json();
    }

    public function read($id) 
    {
        $row = $this->Timrekom_model->get_by_id($id);
        if ($row) {
            $data = array(
		'nama' => $row->nama,
		'nip' => $row->nip,
		'jabatan_tim' => $row->jabatan_tim,
		'kode_usulan' => $row->kode_usulan,
		'id_tim_rekomjak' => $row->id_tim_rekomjak,
	    );
            $this->template->load('template','timrekom/v_timrekom_read', $data);
        } else {
            notif('2');
            redirect(site_url('timrekom'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('timrekom/create_action'),
	    'nama' => set_value('nama'),
	    'nip' => set_value('nip'),
	    'jabatan_tim' => set_value('jabatan_tim'),
	    'kode_usulan' => set_value('kode_usulan'),
	    'id_tim_rekomjak' => set_value('id_tim_rekomjak'),
	);
        $this->template->load('template','timrekom/v_timrekom_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'nip' => $this->input->post('nip',TRUE),
		'jabatan_tim' => $this->input->post('jabatan_tim',TRUE),
		'kode_usulan' => $this->input->post('kode_usulan',TRUE),
		'id_tim_rekomjak' => $this->input->post('id_tim_rekomjak',TRUE),
	    );

            $this->Timrekom_model->insert($data);
            notif('0');
            redirect(site_url('timrekom'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Timrekom_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Perbaharui',
                'action' => site_url('timrekom/update_action'),
		'nama' => set_value('nama', $row->nama),
		'nip' => set_value('nip', $row->nip),
		'jabatan_tim' => set_value('jabatan_tim', $row->jabatan_tim),
		'kode_usulan' => set_value('kode_usulan', $row->kode_usulan),
		'id_tim_rekomjak' => set_value('id_tim_rekomjak', $row->id_tim_rekomjak),
	    );
            $this->template->load('template','timrekom/v_timrekom_form', $data);
        } else {
            notif('2');
            redirect(site_url('timrekom'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'nip' => $this->input->post('nip',TRUE),
		'jabatan_tim' => $this->input->post('jabatan_tim',TRUE),
		'kode_usulan' => $this->input->post('kode_usulan',TRUE),
		'id_tim_rekomjak' => $this->input->post('id_tim_rekomjak',TRUE),
	    );

            $this->Timrekom_model->update($this->input->post('', TRUE), $data);
            notif('1');
            redirect(site_url('timrekom'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Timrekom_model->get_by_id($id);

        if ($row) {
            $this->Timrekom_model->delete($id);
            notif('3');
            redirect(site_url('timrekom'));
        } else {
            notif('2');
            redirect(site_url('timrekom'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('nip', 'nip', 'trim|required');
	$this->form_validation->set_rules('jabatan_tim', 'jabatan tim', 'trim|required');
	$this->form_validation->set_rules('kode_usulan', 'kode usulan', 'trim|required');
	$this->form_validation->set_rules('id_tim_rekomjak', 'id tim rekomjak', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Timrekom.php */
/* Location: ./application/controllers/Timrekom.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 10:00:58 */
/* http://harviacode.com */