<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Usulan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Usulan_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','usulan/v_usulan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Usulan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Usulan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_usulan' => $row->id_usulan,
		'id_instansi_lembaga' => $row->id_instansi_lembaga,
		'nama_instansi_lembaga' => $row->nama_instansi_lembaga,
	    );
            $this->template->load('template','usulan/v_usulan_read', $data);
        } else {
            notif('2');
            redirect(site_url('usulan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('usulan/create_action'),
	    'id_usulan' => set_value('id_usulan'),
	    'id_instansi_lembaga' => set_value('id_instansi_lembaga'),
	    'nama_instansi_lembaga' => set_value('nama_instansi_lembaga'),
	);
        $this->template->load('template','usulan/v_usulan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_usulan' => $this->input->post('id_usulan',TRUE),
		'id_instansi_lembaga' => $this->input->post('id_instansi_lembaga',TRUE),
		'nama_instansi_lembaga' => $this->input->post('nama_instansi_lembaga',TRUE),
	    );

            $this->Usulan_model->insert($data);
            notif('0');
            redirect(site_url('usulan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Usulan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Perbaharui',
                'action' => site_url('usulan/update_action'),
		'id_usulan' => set_value('id_usulan', $row->id_usulan),
		'id_instansi_lembaga' => set_value('id_instansi_lembaga', $row->id_instansi_lembaga),
		'nama_instansi_lembaga' => set_value('nama_instansi_lembaga', $row->nama_instansi_lembaga),
	    );
            $this->template->load('template','usulan/v_usulan_form', $data);
        } else {
            notif('2');
            redirect(site_url('usulan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'id_usulan' => $this->input->post('id_usulan',TRUE),
		'id_instansi_lembaga' => $this->input->post('id_instansi_lembaga',TRUE),
		'nama_instansi_lembaga' => $this->input->post('nama_instansi_lembaga',TRUE),
	    );

            $this->Usulan_model->update($this->input->post('', TRUE), $data);
            notif('1');
            redirect(site_url('usulan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Usulan_model->get_by_id($id);

        if ($row) {
            $this->Usulan_model->delete($id);
            notif('3');
            redirect(site_url('usulan'));
        } else {
            notif('2');
            redirect(site_url('usulan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_usulan', 'id usulan', 'trim|required');
	$this->form_validation->set_rules('id_instansi_lembaga', 'id instansi lembaga', 'trim|required');
	$this->form_validation->set_rules('nama_instansi_lembaga', 'nama instansi lembaga', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Usulan.php */
/* Location: ./application/controllers/Usulan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-04 06:13:09 */
/* http://harviacode.com */