<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Calon_model extends CI_Model
{

    public $table = 'v_calon';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kode_usulan,id_calon_rekomjak,full_name,arahan_pimpinan,status_calon_rekomjak,created_by,created_date,modified_by,modified_date');
        $this->datatables->from('v_calon');
        //add this line for join
        //$this->datatables->join('table2', 'v_calon.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('calon/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('calon/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('calon/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), '');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('kode_usulan', $q);
	$this->db->or_like('id_calon_rekomjak', $q);
	$this->db->or_like('full_name', $q);
	$this->db->or_like('arahan_pimpinan', $q);
	$this->db->or_like('status_calon_rekomjak', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('kode_usulan', $q);
	$this->db->or_like('id_calon_rekomjak', $q);
	$this->db->or_like('full_name', $q);
	$this->db->or_like('arahan_pimpinan', $q);
	$this->db->or_like('status_calon_rekomjak', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Calon_model.php */
/* Location: ./application/models/Calon_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:55:22 */
/* http://harviacode.com */