<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dinkes_prov_model extends CI_Model
{

    public $table = 't_dinkes_prov';
    public $id = 'id_dinkes_prov';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_dinkes_prov,nama_dinkes_prov');
        $this->datatables->from('t_dinkes_prov');
        //add this line for join
        //$this->datatables->join('table2', 't_dinkes_prov.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('dinkes_prov/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('dinkes_prov/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('dinkes_prov/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), 'id_dinkes_prov');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_dinkes_prov', $q);
	$this->db->or_like('nama_dinkes_prov', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dinkes_prov', $q);
	$this->db->or_like('nama_dinkes_prov', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dinkes_prov_model.php */
/* Location: ./application/models/Dinkes_prov_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:09:21 */
/* http://harviacode.com */