<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_kegiatan_model extends CI_Model
{

    public $table = 't_jenis_kegiatan';
    public $id = 'id_jenis_kegiatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_jenis_kegiatan,nama_kegiatan');
        $this->datatables->from('t_jenis_kegiatan');
        //add this line for join
        //$this->datatables->join('table2', 't_jenis_kegiatan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jenis_kegiatan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('jenis_kegiatan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('jenis_kegiatan/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), 'id_jenis_kegiatan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jenis_kegiatan', $q);
	$this->db->or_like('nama_kegiatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jenis_kegiatan', $q);
	$this->db->or_like('nama_kegiatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jenis_kegiatan_model.php */
/* Location: ./application/models/Jenis_kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:11:25 */
/* http://harviacode.com */