<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pegawai_data_model extends CI_Model
{

    public $table = 'pegawai_data';
    public $id = 'id_pegawai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pegawai,nama,nip,golongan,jabatan,nik,tempat_lahir,tgl_lahir,jenis_kelamin,alamat,telp,email,status_menikah,created_by,created_date,modified_by,modified_date');
        $this->datatables->from('pegawai_data');
        //add this line for join
        //$this->datatables->join('table2', 'pegawai_data.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pegawai_data/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('pegawai_data/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('pegawai_data/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), 'id_pegawai');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pegawai', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('status_menikah', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pegawai', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('status_menikah', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pegawai_data_model.php */
/* Location: ./application/models/Pegawai_data_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:04:25 */
/* http://harviacode.com */