<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Unit_utama_model extends CI_Model
{

    public $table = 't_unit_utama';
    public $id = 'id_unit_utama';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_unit_utama,nama_unit_utama');
        $this->datatables->from('t_unit_utama');
        //add this line for join
        //$this->datatables->join('table2', 't_unit_utama.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('unit_utama/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('unit_utama/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('unit_utama/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), 'id_unit_utama');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_unit_utama', $q);
	$this->db->or_like('nama_unit_utama', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_unit_utama', $q);
	$this->db->or_like('nama_unit_utama', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Unit_utama_model.php */
/* Location: ./application/models/Unit_utama_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:13:14 */
/* http://harviacode.com */