<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Usulan_model extends CI_Model
{

    public $table = 'v_usulan';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kode_usulan,nama_pengusul,jabatan_pengusul,surat_usulan,tahun_usulan,latar_belakang,identifikasi_masalah,tujuan,catatan,telepon,email,status_usulan,created_by,created_date,modified_by,modified_date,nama_instansi_lembaga,nama_unit_utama,nama_satuan_kerja,nama_dinkes_kab,Satuan_Kerja,id_usulan');
        $this->datatables->from('v_usulan');
        //add this line for join
        //$this->datatables->join('table2', 'v_usulan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('usulan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('usulan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('usulan/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), '');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('kode_usulan', $q);
	$this->db->or_like('nama_pengusul', $q);
	$this->db->or_like('jabatan_pengusul', $q);
	$this->db->or_like('surat_usulan', $q);
	$this->db->or_like('tahun_usulan', $q);
	$this->db->or_like('latar_belakang', $q);
	$this->db->or_like('identifikasi_masalah', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('catatan', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('status_usulan', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->or_like('nama_instansi_lembaga', $q);
	$this->db->or_like('nama_unit_utama', $q);
	$this->db->or_like('nama_satuan_kerja', $q);
	$this->db->or_like('nama_dinkes_kab', $q);
	$this->db->or_like('Satuan_Kerja', $q);
	$this->db->or_like('id_usulan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('kode_usulan', $q);
	$this->db->or_like('nama_pengusul', $q);
	$this->db->or_like('jabatan_pengusul', $q);
	$this->db->or_like('surat_usulan', $q);
	$this->db->or_like('tahun_usulan', $q);
	$this->db->or_like('latar_belakang', $q);
	$this->db->or_like('identifikasi_masalah', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('catatan', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('status_usulan', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->or_like('nama_instansi_lembaga', $q);
	$this->db->or_like('nama_unit_utama', $q);
	$this->db->or_like('nama_satuan_kerja', $q);
	$this->db->or_like('nama_dinkes_kab', $q);
	$this->db->or_like('Satuan_Kerja', $q);
	$this->db->or_like('id_usulan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Usulan_model.php */
/* Location: ./application/models/Usulan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-09 09:37:21 */
/* http://harviacode.com */